name: play_me
description: PlayMe Music Player

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  dart_vlc: ^0.0.6
  font_awesome_flutter: ^9.0.0
  file_selector_platform_interface: ^2.0.0
  file_selector_windows: ^0.0.2
  provider: ^5.0.0
  bitsdojo_window: ^0.1.0+1
  shared_preferences_platform_interface: ^2.0.0
  shared_preferences: ^2.0.5
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  msix: ^2.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/images/PlayMeLogo.png
   - assets/images/PlayMe.gif

  fonts:
    - family: Courgette
      fonts:
        - asset: assets/fonts/Courgette-Regular.ttf

msix_config:
  display_name: PlayMe
  publisher_display_name: Uditha Ishan
  identity_name: lk.devstream.playme
  msix_version: 2.0.0.0
  logo_path: C:\Users\Uditha Ishan\Downloads\PlayMeLogo (3).png
  publisher: CN=Uditha Ishan, O=DevStream-LK, L=Galle, S=Southern, C=LK